package io.github.thomaskioko.gradle.tasks

import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.ProjectLayout
import org.gradle.api.model.ObjectFactory
import org.gradle.api.provider.MapProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import javax.inject.Inject

/**
 * Gradle task that generates a BuildConfig.kt file with compile-time constants.
 *
 * This task reads configuration from the BuildConfigExtension and generates
 * a Kotlin object with public constants. All values are embedded at compile-time.
 *
 */
@CacheableTask
public abstract class BuildConfigGeneratorTask
@Inject constructor(
    objectFactory: ObjectFactory,
    layout: ProjectLayout,
) : DefaultTask() {

    init {
        description = "Generates BuildConfig.kt with compile-time constants"
        group = "build"
    }

    /**
     * The package name for the generated BuildConfig class.
     */
    @get:Input
    public abstract val packageName: Property<String>

    /**
     * Custom string fields to add to BuildConfig.
     */
    @get:Input
    public abstract val stringFields: MapProperty<String, String>

    /**
     * Custom boolean fields to add to BuildConfig.
     */
    @get:Input
    public abstract val booleanFields: MapProperty<String, Boolean>

    /**
     * Custom int fields to add to BuildConfig.
     */
    @get:Input
    public abstract val intFields: MapProperty<String, Int>

    /**
     * Output directory for the generated BuildConfig.kt file.
     * Defaults to build/generated/buildconfig/commonMain/kotlin
     */
    @get:OutputDirectory
    public val outputDirectory: DirectoryProperty = objectFactory.directoryProperty()
        .convention(layout.buildDirectory.dir("generated/buildconfig/commonMain/kotlin"))

    @TaskAction
    public fun generate() {
        val outputDir = outputDirectory.get().asFile
        val pkg = packageName.get()

        // Validate package name format
        require(pkg.matches(Regex("^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)*$"))) {
            "Invalid package name: '$pkg'. Package names must start with a lowercase letter and contain only lowercase letters, numbers, underscores, and dots."
        }

        val customStrings = stringFields.get()
        val customBooleans = booleanFields.get()
        val customInts = intFields.get()

        outputDir.deleteRecursively()
        outputDir.mkdirs()

        val buildConfigBuilder = TypeSpec.objectBuilder("BuildConfig")
            .addKdoc(
                """
                |Build configuration constants generated at compile-time.
                |
                |DO NOT EDIT - This file is auto-generated by BuildConfigGeneratorTask.
                |
                |To modify these values, update your build.gradle.kts:
                |```
                |buildConfig {
                |    packageName.set("$pkg")
                |    stringField("FIELD_NAME", "value")
                |    booleanField("FIELD_NAME", true)
                |    intField("FIELD_NAME", 42)
                |}
                |```
                """.trimMargin(),
            )

        // Add custom string fields
        customStrings.forEach { (name, value) ->
            buildConfigBuilder.addProperty(
                PropertySpec.builder(name, String::class)
                    .addModifiers(KModifier.CONST)
                    .initializer("%S", value)
                    .build(),
            )
        }

        // Add custom boolean fields
        customBooleans.forEach { (name, value) ->
            buildConfigBuilder.addProperty(
                PropertySpec.builder(name, Boolean::class)
                    .addModifiers(KModifier.CONST)
                    .initializer("%L", value)
                    .build(),
            )
        }

        // Add custom int fields
        customInts.forEach { (name, value) ->
            buildConfigBuilder.addProperty(
                PropertySpec.builder(name, Int::class)
                    .addModifiers(KModifier.CONST)
                    .initializer("%L", value)
                    .build(),
            )
        }

        // Write to file
        FileSpec.builder(pkg, "BuildConfig")
            .addType(buildConfigBuilder.build())
            .indent("    ") // 4-space indentation
            .build()
            .writeTo(outputDir)
    }
}
