package io.github.thomaskioko.gradle.plugins.functional

import org.gradle.testkit.runner.TaskOutcome
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder
import java.io.File

/**
 * Exercises the Gradle wiring of `useFeatureFlagCodegen()` end to end against a real KMP build.
 *
 * The fixture resolves `codegen-featureflag-annotations` and `codegen-featureflag-processor` from
 * `mavenLocal`, so the feature-flag codegen artifacts must be published locally before this test
 * runs. The root `publishLocal` task publishes them; CI runs it in a dedicated step ahead of
 * `:plugins:functionalTest`.
 */
class FeatureFlagCodegenFunctionalTest {
    @get:Rule
    val tempFolder = TemporaryFolder()

    @Test
    fun `useFeatureFlagCodegen generates the qualifier and binding for a commonMain anchor`() {
        val project = Fixtures.extract("featureflag-codegen", tempFolder.newFolder("project"))

        val result = project.compositeRunner(":feature:kspCommonMainKotlinMetadata").build()

        assertEquals(
            TaskOutcome.SUCCESS,
            result.task(":feature:kspCommonMainKotlinMetadata")?.outcome,
        )

        val generated = metadataGeneratedFiles(project.rootDir)

        assertTrue(
            "Expected generated qualifier SimklLoginFlagQualifier.kt in the commonMain metadata " +
                "output, but found $generated",
            generated.contains("SimklLoginFlagQualifier.kt"),
        )
        assertTrue(
            "Expected generated binding SimklLoginFlagBinding.kt in the commonMain metadata " +
                "output, but found $generated",
            generated.contains("SimklLoginFlagBinding.kt"),
        )
    }

    @Test
    fun `platform IOS anchor generates only under the iOS targets and ALL anchor generates once`() {
        val project = Fixtures.extract("featureflag-codegen", tempFolder.newFolder("project"))

        val result = project.compositeRunner(
            ":feature:kspCommonMainKotlinMetadata",
            ":feature:kspKotlinIosSimulatorArm64",
            ":feature:kspKotlinJvm",
        ).build()

        assertEquals(
            TaskOutcome.SUCCESS,
            result.task(":feature:kspCommonMainKotlinMetadata")?.outcome,
        )
        assertEquals(
            TaskOutcome.SUCCESS,
            result.task(":feature:kspKotlinIosSimulatorArm64")?.outcome,
        )
        assertEquals(
            TaskOutcome.SUCCESS,
            result.task(":feature:kspKotlinJvm")?.outcome,
        )

        val tree = generatedTree(project.rootDir)

        val metadataFiles = filesUnder(tree, "metadata")
        val iosSimulatorFiles = filesUnder(tree, "iosSimulatorArm64")
        val jvmFiles = filesUnder(tree, "jvm")

        // commonMain anchor: generated exactly once, by the metadata run only.
        assertTrue(
            "Expected the commonMain SimklLoginFlag pair under the metadata run, tree was:\n$tree",
            metadataFiles.containsAll(
                setOf("SimklLoginFlagQualifier.kt", "SimklLoginFlagBinding.kt"),
            ),
        )
        assertEquals(
            "commonMain anchor must not be regenerated by the iOS per-target run, tree was:\n$tree",
            emptySet<String>(),
            iosSimulatorFiles.filter { it.startsWith("SimklLoginFlag") }.toSet(),
        )
        assertEquals(
            "commonMain anchor must not be regenerated by the JVM per-target run, tree was:\n$tree",
            emptySet<String>(),
            jvmFiles.filter { it.startsWith("SimklLoginFlag") }.toSet(),
        )

        // platform = IOS anchor (declared in commonMain): generated only under the iOS targets.
        assertTrue(
            "Expected the platform=IOS EnableLiquidGlassFlag pair under the iOS target, tree was:\n$tree",
            iosSimulatorFiles.containsAll(
                setOf("EnableLiquidGlassFlagQualifier.kt", "EnableLiquidGlassFlagBinding.kt"),
            ),
        )
        assertEquals(
            "platform=IOS anchor must be absent from the commonMain metadata run, tree was:\n$tree",
            emptySet<String>(),
            metadataFiles.filter { it.startsWith("EnableLiquidGlassFlag") }.toSet(),
        )
        assertEquals(
            "platform=IOS anchor must be absent from the JVM run, tree was:\n$tree",
            emptySet<String>(),
            jvmFiles.filter { it.startsWith("EnableLiquidGlassFlag") }.toSet(),
        )
    }

    private fun metadataGeneratedFiles(rootDir: File): Set<String> {
        val dir = File(
            rootDir,
            "feature/build/generated/ksp/metadata/commonMain/kotlin/" +
                "com/thomaskioko/tvmaniac/featureflags/flags",
        )
        return dir.listFiles()?.map { it.name }?.toSet().orEmpty()
    }

    private fun generatedTree(rootDir: File): String {
        val root = File(rootDir, "feature/build/generated/ksp")
        if (!root.exists()) return "<no ksp output>"
        return root.walkTopDown()
            .filter { it.isFile && it.extension == "kt" }
            .map { it.relativeTo(root).path }
            .sorted()
            .joinToString("\n")
    }

    private fun filesUnder(tree: String, firstSegment: String): Set<String> =
        tree.lineSequence()
            .filter { it.substringBefore('/') == firstSegment }
            .map { it.substringAfterLast('/') }
            .toSet()
}
