package io.github.thomaskioko.codegen.featureflag.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.PlatformInfo
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSAnnotation
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.ksp.writeTo

/**
 * KSP processor that turns `@FeatureFlag`-decorated anchors into a Metro `@Qualifier` annotation
 * and a binding interface. Loaded once per build by KSP through [FeatureFlagCodegenProcessorProvider].
 *
 * For each annotated symbol the processor validates the shape (class/object/interface — not an
 * annotation class — with non-blank `key` and `title` and an ISO-formatted `dateAdded`), parses the
 * annotation arguments, takes the base name from the anchor's simple name verbatim, and hands the
 * result to [FeatureFlagQualifierGenerator] and [FeatureFlagBindingGenerator], which emit one
 * `<BaseName>Qualifier.kt` and one `<BaseName>Binding.kt` file into the anchor's package. Validation
 * failures are reported through [KSPLogger.error] pinned to the offending symbol so KSP turns them
 * into compile errors at the source position, rather than thrown; the annotation-argument readers
 * assume KSP has already guaranteed the required members are present.
 *
 * The DSL attaches the processor to the `commonMain` metadata run and every per-target run, so a
 * [PlatformSourceSetGuard] keeps a single run as the one that emits each anchor. The anchor's
 * `platform` field drives this: a [FlagPlatform.ALL] flag is generated by the metadata run alone,
 * while a `platform = IOS`/`JVM` flag is generated only by the matching per-target run. The guard
 * runs before validation so a malformed anchor reports its error once, from the run that owns it,
 * rather than once per compilation.
 *
 * @property codeGenerator KSP's file writer. Receives every produced [FileSpec].
 * @property logger KSP's diagnostic sink. Reports validation errors pinned to symbols.
 * @property platforms Target platforms for the current KSP run, used to build the guard.
 */
public class FeatureFlagCodegenProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
    platforms: List<PlatformInfo>,
) : SymbolProcessor {

    private val sourceSetGuard = PlatformSourceSetGuard(platforms)

    /**
     * Runs one KSP round. Iterates every symbol annotated with `@FeatureFlag`, skips anchors the
     * current run does not own, validates and parses the rest into a [FeatureFlagData], and writes
     * one qualifier and one binding file per owned anchor.
     *
     * @param resolver KSP's lookup interface for the current round.
     * @return An empty list. The processor does not defer work to later rounds.
     */
    override fun process(resolver: Resolver): List<KSAnnotated> {
        for (symbol in resolver.getSymbolsWithAnnotation(FEATURE_FLAG_FQN)) {
            val declaration = symbol as? KSClassDeclaration ?: run {
                logger.error(
                    "[FeatureFlag/InvalidTarget] @FeatureFlag must annotate a class, object, or " +
                        "interface. Saw it on a non-class symbol.",
                    symbol,
                )
                continue
            }
            val containingFile = declaration.containingFile ?: continue
            if (!sourceSetGuard.shouldGenerateFor(declaration.featureFlagPlatform(), containingFile)) continue
            val data = parse(declaration) ?: continue
            writeFile(declaration, FeatureFlagQualifierGenerator.generate(data))
            writeFile(declaration, FeatureFlagBindingGenerator.generate(data))
        }
        return emptyList()
    }

    /**
     * Validates and parses the `@FeatureFlag` annotation on [declaration].
     *
     * Returns `null` and logs a compile error via [KSPLogger.error] when any validation rule fails:
     * the target is an annotation class, `key` is blank, `title` is blank, or `dateAdded` does not
     * parse as an ISO `YYYY-MM-DD` date.
     */
    private fun parse(declaration: KSClassDeclaration): FeatureFlagData? {
        val anchorName = declaration.simpleName.asString()

        if (declaration.classKind == ClassKind.ANNOTATION_CLASS) {
            logger.error(
                "[FeatureFlag/InvalidTarget] @FeatureFlag must annotate a class, object, or " +
                    "interface, not an annotation class. The qualifier is generated for you. " +
                    "Saw @$anchorName declared as an annotation class.",
                declaration,
            )
            return null
        }

        val annotation = declaration.annotations.firstOrNull { it.shortName.asString() == FEATURE_FLAG_SHORT_NAME }
            ?: run {
                logger.error("Missing @FeatureFlag annotation", declaration)
                return null
            }

        val key = annotation.stringArgument("key")
        if (key.isBlank()) {
            logger.error(
                "[FeatureFlag/EmptyKey] @FeatureFlag(key = \"\") on $anchorName is invalid. " +
                    "Provide the Firebase Remote Config key.",
                declaration,
            )
            return null
        }

        val title = annotation.stringArgument("title")
        if (title.isBlank()) {
            logger.error(
                "[FeatureFlag/EmptyTitle] @FeatureFlag(title = \"\") on $anchorName is invalid. " +
                    "Provide the debug-screen title.",
                declaration,
            )
            return null
        }

        val description = annotation.stringArgument("description")
        if (description.isBlank()) {
            logger.error(
                "[FeatureFlag/EmptyDescription] @FeatureFlag(description = \"\") on $anchorName is invalid. " +
                    "Provide the one-line summary shown beneath the title on the debug screen.",
                declaration,
            )
            return null
        }

        val defaultValue = annotation.booleanArgument("defaultValue")
        val dateAdded = annotation.stringArgument("dateAdded")
        val date = parseIsoDate(dateAdded)
        if (date == null) {
            logger.error(
                "[FeatureFlag/InvalidDate] @FeatureFlag(dateAdded = \"$dateAdded\") on " +
                    "$anchorName is not a valid ISO date (YYYY-MM-DD).",
                declaration,
            )
            return null
        }

        val packageName = declaration.packageName.asString()
        val baseName = anchorName

        return FeatureFlagData(
            packageName = packageName,
            qualifierClassName = ClassName(packageName, "$baseName$QUALIFIER_SUFFIX"),
            baseName = baseName,
            key = key,
            title = title,
            description = description,
            defaultValue = defaultValue,
            year = date.year,
            month = date.month,
            day = date.day,
        )
    }

    /**
     * Writes [file] to disk via KSP's [CodeGenerator]. Uses `aggregating = false` so the output
     * depends only on the source file the annotation lives in; editing one flag does not
     * invalidate sibling flags.
     */
    private fun writeFile(source: KSClassDeclaration, file: FileSpec) {
        val containingFile = source.containingFile ?: run {
            logger.warn("Cannot determine containing file for ${source.qualifiedName?.asString()}", source)
            return
        }
        file.writeTo(codeGenerator, Dependencies(aggregating = false, containingFile))
    }

    private fun KSAnnotation.stringArgument(name: String): String {
        val value = arguments.firstOrNull { it.name?.asString() == name }?.value
            ?: defaultArguments.firstOrNull { it.name?.asString() == name }?.value
            ?: error("@FeatureFlag missing required '$name' argument")
        return value as? String
            ?: error("@FeatureFlag '$name' argument is not a String (got ${value::class.simpleName})")
    }

    private fun KSAnnotation.booleanArgument(name: String): Boolean {
        val value = arguments.firstOrNull { it.name?.asString() == name }?.value
            ?: defaultArguments.firstOrNull { it.name?.asString() == name }?.value
            ?: error("@FeatureFlag missing required '$name' argument")
        return value as? Boolean
            ?: error("@FeatureFlag '$name' argument is not a Boolean (got ${value::class.simpleName})")
    }

    /**
     * Reads the `platform` argument as a [FlagPlatform]. The processor matches by simple name rather
     * than depending on the annotations artifact; an absent or unrecognized value is [FlagPlatform.ALL].
     */
    private fun KSClassDeclaration.featureFlagPlatform(): FlagPlatform {
        val annotation = annotations.firstOrNull { it.shortName.asString() == FEATURE_FLAG_SHORT_NAME }
            ?: return FlagPlatform.ALL
        val value = annotation.arguments.firstOrNull { it.name?.asString() == "platform" }?.value
            ?: return FlagPlatform.ALL
        val name = when (value) {
            is KSType -> value.declaration.simpleName.asString()
            is KSClassDeclaration -> value.simpleName.asString()
            else -> value.toString().substringAfterLast('.')
        }
        return when (name.uppercase()) {
            "IOS" -> FlagPlatform.IOS
            "JVM" -> FlagPlatform.JVM
            else -> FlagPlatform.ALL
        }
    }

    private fun parseIsoDate(value: String): IsoDate? {
        val parts = value.split('-')
        if (parts.size != 3) return null
        val year = parts[0].toIntOrNull() ?: return null
        val month = parts[1].toIntOrNull() ?: return null
        val day = parts[2].toIntOrNull() ?: return null
        if (month !in 1..12) return null
        if (day !in 1..31) return null
        return IsoDate(year, month, day)
    }

    private data class IsoDate(val year: Int, val month: Int, val day: Int)

    internal companion object {
        internal const val FEATURE_FLAG_FQN: String = "io.github.thomaskioko.codegen.annotations.FeatureFlag"
        internal const val FEATURE_FLAG_SHORT_NAME: String = "FeatureFlag"
        internal const val QUALIFIER_SUFFIX: String = "Qualifier"
    }
}
