package io.github.thomaskioko.codegen.featureflag.processor

import com.google.devtools.ksp.processing.JvmPlatformInfo
import com.google.devtools.ksp.processing.NativePlatformInfo
import com.google.devtools.ksp.processing.PlatformInfo
import com.google.devtools.ksp.symbol.KSFile

/**
 * The platform a `@FeatureFlag` anchor is scoped to, read from the annotation's `platform` argument.
 *
 * Mirrors the consumer-facing `io.github.thomaskioko.codegen.annotations.Platform` enum by name. The
 * processor reads the annotation by string and does not depend on the annotations artifact, so the
 * value is matched on its simple name; an unrecognized or absent value falls back to [ALL].
 */
internal enum class FlagPlatform { ALL, IOS, JVM }

/**
 * Decides whether a `@FeatureFlag` anchor belongs to the compilation KSP is running for, so each
 * anchor is generated exactly once into exactly one compilation's view.
 *
 * The DSL attaches the processor to the `commonMain` metadata run and every per-target run through
 * `addKspDependencyForAllTargets`. The anchor's `platform` field selects the routing while the
 * anchor itself stays in `commonMain` (which every per-target run sees):
 *
 * - [FlagPlatform.IOS] / [FlagPlatform.JVM] — generated only by the matching per-target run
 *   ([NativePlatformInfo] for iOS, [JvmPlatformInfo] for the Android/JVM family) and skipped
 *   everywhere else.
 * - [FlagPlatform.ALL] — generated by the `commonMain` metadata run and skipped by the classified
 *   per-target runs, so it reaches both graphs without redeclaring. When neither the run nor the
 *   anchor's source set can be classified (a single-platform `src/main` layout, or the synthetic
 *   paths a hermetic compile-testing run uses) the flag is generated rather than suppressed.
 *
 * @property platforms Target platforms for the current KSP run. A metadata run carries more than one
 *   entry; a per-target run carries exactly one.
 */
internal class PlatformSourceSetGuard(
    private val platforms: List<PlatformInfo>,
) {

    private val runGroup: TargetGroup? = resolveRunGroup(platforms)

    /**
     * Returns `true` when the anchor with [platform] in [file] should be generated for the current
     * run. A scoped flag emits only from its platform's per-target run (or when the run is
     * unclassifiable); an [FlagPlatform.ALL] flag follows the source-set routing in
     * [shouldGenerateUnscopedFor].
     */
    fun shouldGenerateFor(platform: FlagPlatform, file: KSFile): Boolean = when (platform) {
        FlagPlatform.IOS -> runGroup == null || runGroup == TargetGroup.NATIVE
        FlagPlatform.JVM -> runGroup == null || runGroup == TargetGroup.JVM
        FlagPlatform.ALL -> shouldGenerateUnscopedFor(file)
    }

    private fun shouldGenerateUnscopedFor(file: KSFile): Boolean {
        val run = runGroup ?: return true
        val anchor = anchorGroup(file.filePath) ?: return true
        return anchor == run
    }

    private fun anchorGroup(filePath: String): TargetGroup? {
        val sourceSet = sourceSetName(filePath) ?: return null
        return when {
            sourceSet == COMMON_MAIN -> TargetGroup.COMMON
            sourceSet == ANDROID_MAIN || sourceSet == JVM_MAIN -> TargetGroup.JVM
            NATIVE_SOURCE_SET_TOKENS.any { sourceSet.contains(it, ignoreCase = true) } -> TargetGroup.NATIVE
            else -> null
        }
    }

    private fun sourceSetName(filePath: String): String? {
        val segments = filePath.split('/', '\\')
        val srcIndex = segments.lastIndexOf(SRC_SEGMENT)
        if (srcIndex == -1 || srcIndex == segments.lastIndex) return null
        return segments[srcIndex + 1]
    }

    private enum class TargetGroup { COMMON, NATIVE, JVM }

    private companion object {
        private const val SRC_SEGMENT = "src"
        private const val COMMON_MAIN = "commonMain"
        private const val ANDROID_MAIN = "androidMain"
        private const val JVM_MAIN = "jvmMain"
        private val NATIVE_SOURCE_SET_TOKENS = listOf(
            "ios",
            "apple",
            "native",
            "macos",
            "tvos",
            "watchos",
            "linux",
            "mingw",
        )

        private fun resolveRunGroup(platforms: List<PlatformInfo>): TargetGroup? = when {
            platforms.size > 1 -> TargetGroup.COMMON

            platforms.size == 1 -> when (platforms.single()) {
                is NativePlatformInfo -> TargetGroup.NATIVE
                is JvmPlatformInfo -> TargetGroup.JVM
                else -> null
            }

            else -> null
        }
    }
}
