package io.github.thomaskioko.codegen.processor.codegen

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.TypeSpec
import io.github.thomaskioko.codegen.processor.util.FOUR_SPACE_INDENT
import io.github.thomaskioko.codegen.processor.util.contributesTo

/**
 * Builds a binding file structured as
 * `@ContributesTo(parentScope) public interface [bindingName] { public companion object { ... } }`
 * with the supplied [providers] declared inside the companion. Both
 * [NavDestinationBindingGenerator] and [TabDestinationBindingGenerator] call this helper so
 * neither has to spell the scaffold out itself.
 *
 * The structure is fixed: an interface whose companion holds `@Provides @IntoSet` functions. The
 * bindings the codegen emits for `@ScreenUi` and `@SheetUi` composables use a different
 * structure (`@BindingContainer object`) and are generated by [UiBindingGenerator] without
 * going through this helper. The reason for the divergence is documented on [UiBindingGenerator].
 *
 * @param bindingName The class name of the generated binding interface.
 * @param parentScope The parent dependency injection scope the binding contributes to.
 * @param providers The `@Provides @IntoSet` functions to declare inside the companion object.
 * @return A KotlinPoet [FileSpec] containing the binding interface and its companion.
 */
internal fun contributingBindingFile(
    bindingName: ClassName,
    parentScope: ClassName,
    vararg providers: FunSpec,
): FileSpec {
    val companion = TypeSpec.companionObjectBuilder()
        .addModifiers(KModifier.PUBLIC)
        .also { builder -> providers.forEach { builder.addFunction(it) } }
        .build()

    val bindingInterface = TypeSpec.interfaceBuilder(bindingName)
        .addModifiers(KModifier.PUBLIC)
        .addAnnotation(contributesTo(parentScope))
        .addType(companion)
        .build()

    return FileSpec.builder(bindingName)
        .indent(FOUR_SPACE_INDENT)
        .addType(bindingInterface)
        .build()
}
